comment = "comment"

host = [
    "localhost",
    "192.168.199.234",
]

find = "find /tmp/ -regex '/tmp/.*' -mtime -1 -name '*?log*'"

[[monitor_items]]
search_pattern=""
alert=""
check_interval=""
trigger_format=""
dingding_webhook=""
comment=""

[[monitor_items]]
search_pattern=""
alert=""
check_interval=""
trigger_format=""
dingding_webhook=""
comment=""